---
- name: Copy auto_compound file
  template:
    src: 'auto_compounder.sh.j2'
    dest: '/home/{{ ansible_user }}/{{network}}_auto_compounder.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0700'

- name: Be a degen and create cronjob
  cron:
    user: '{{ ansible_user }}'
    name: '{{ network }} auto compounder'
    minute: '{{ auto_compounder_minute }}'
    hour: '{{ auto_compounder_hour }}'
    day: '{{ auto_compounder_day }}'
    job: '/bin/bash /home/{{ ansible_user }}/{{network}}_auto_compounder.sh'
  when: cron is defined and cron|bool == true
